exports.querylist ={

    GET_STORE_LIST_QUERY :'SELECT STORE_ID, STORE_NAME, STORE_ADDRESS, STORE_CODE FROM BMS.STORE' ,

    SAVE_STORE_QUERY : 'INSERT INTO BMS.STORE (STORE_NAME, STORE_CODE, STORE_ADDRESS , CREATED_BY , CREATED_ON) VALUES($1, $2, $3, $4, $5)',

    GET_BOOK_LIST_QUERY : 'SELECT BOOK_ID, BOOK_TITLE, BOOK_AUTHOR, BOOK_PUBLISHER FROM BMS.BOOK',

    GET_BOOK_DETAILS_LIST_QUERY : `SELECT BOOK_ID, BOOK_TITLE, BOOK_AUTHOR, BOOK_PUBLISHER,BOOK_DESCRIPTION, BOOK_PAGES, BOOK.STORE_CODE,
                                   STORE.STORE_NAME ,STORE.STORE_ADDRESS  FROM BMS.BOOK
                                   INNER JOIN BMS.STORE ON BOOK.STORE_CODE =STORE.STORE_CODE
                                   WHERE BOOK_ID  = $1 `,
                                     
                                 
   SAVE_BOOK_QUERY  :  `INSERT INTO BMS.BOOK
                        (BOOK_TITLE, BOOK_AUTHOR, BOOK_PUBLISHER, BOOK_DESCRIPTION, BOOK_PAGES, STORE_CODE, CREATED_BY, CREATED_ON)
                         VALUES($1, $2,$3,$4, $5, $6,$7,$8);`,
}